"""
Export a domain-assistant conversation (shock / tie-down / mobility) to Markdown
or a self-contained HTML file.

Pure functions -- NO Streamlit dependency, so they are unit-testable and shared by
all three in-tab assistants via render_domain_assistant() in app.py.

History shape (app.py session_state["asst_<domain>_history"]):
  {"role": "user", "content": "..."}
  {"role": "assistant", "content": "...", "events": [{type,name,args,content}, ...]}
"""
from __future__ import annotations

import re
from datetime import datetime
from html import escape

_MAX_RESULT_CHARS = 1200


def _short(text: str, limit: int = _MAX_RESULT_CHARS) -> str:
    text = text or ""
    if len(text) <= limit:
        return text
    return text[:limit] + f"\n... ({len(text) - limit} more characters truncated)"


def _count_turns(history) -> int:
    return sum(1 for m in (history or []) if m.get("role") == "user")


# ---------------------------------------------------------------------------
# Markdown export
# ---------------------------------------------------------------------------
def _events_md(events) -> list:
    lines = []
    for ev in events or []:
        t = ev.get("type")
        if t == "tool_call":
            args = ", ".join(f"{k}={v!r}" for k, v in (ev.get("args") or {}).items())
            lines.append(f"- **`{ev.get('name')}`**({args})")
        elif t == "tool_result":
            lines.append(f"- `{ev.get('name')}` returned:")
            lines.append("  ```")
            for ln in _short(ev.get("content", "")).splitlines():
                lines.append(f"  {ln}")
            lines.append("  ```")
    return lines


def history_to_markdown(history, title: str = "Assistant conversation") -> str:
    """Render the conversation as a portable Markdown document."""
    ts = datetime.now().strftime("%Y-%m-%d %H:%M")
    out = [f"# {title}", "",
           f"*Exported {ts} - {_count_turns(history)} exchange(s)*",
           "", "_Every number in the answers comes from a validated engine tool, "
           "never generated by the language model._", ""]
    for msg in history or []:
        role = msg.get("role")
        content = (msg.get("content") or "").strip()
        if role == "user":
            out += ["---", "", "### You", "", content, ""]
        else:
            out += ["### Assistant", ""]
            steps = _events_md(msg.get("events"))
            if steps:
                out += ["**Agent steps (tool calls):**", ""]
                out += steps
                out += [""]
            out += [content or "*(no answer)*", ""]
    return "\n".join(out)


# ---------------------------------------------------------------------------
# HTML export
# ---------------------------------------------------------------------------
def _md_inline(text: str) -> str:
    """Escape, then apply a tiny markdown subset: **bold** and `code`."""
    s = escape(text or "")
    s = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", s)
    s = re.sub(r"`([^`]+?)`", r"<code>\1</code>", s)
    return s


def _answer_html(text: str) -> str:
    """Render the assistant answer: paragraphs, line breaks and bullet lists."""
    blocks = []
    for para in (text or "").split("\n\n"):
        lines = [ln for ln in para.splitlines()]
        nonblank = [ln for ln in lines if ln.strip()]
        if nonblank and all(ln.strip()[:2] in ("- ", "* ") or ln.strip()[:2] == "• "
                            for ln in nonblank):
            items = "".join(f"<li>{_md_inline(ln.strip()[2:])}</li>" for ln in nonblank)
            blocks.append(f"<ul>{items}</ul>")
        elif nonblank:
            blocks.append("<p>" + "<br>".join(_md_inline(ln) for ln in lines) + "</p>")
    return "\n".join(blocks)


def _events_html(events) -> str:
    rows = []
    for ev in events or []:
        t = ev.get("type")
        if t == "tool_call":
            args = ", ".join(f"{k}={v!r}" for k, v in (ev.get("args") or {}).items())
            rows.append(f'<div class="step">&#128295; <code>{escape(str(ev.get("name")))}</code>'
                        f'(<span class="args">{escape(args)}</span>)</div>')
        elif t == "tool_result":
            rows.append(f'<div class="step">&#9989; <code>{escape(str(ev.get("name")))}</code> '
                        f'returned:<pre>{escape(_short(ev.get("content", "")))}</pre></div>')
    if not rows:
        return ""
    return ('<details class="steps"><summary>Agent steps (tool calls)</summary>'
            + "".join(rows) + "</details>")


_HTML_CSS = """
:root { color-scheme: light dark; }
body { font-family: -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif;
       max-width: 820px; margin: 2rem auto; padding: 0 1rem; line-height: 1.55;
       color: #1a1a1a; background: #fafafa; }
h1 { font-size: 1.5rem; margin-bottom: .25rem; }
.meta { color: #666; font-size: .85rem; margin-bottom: 1.5rem; }
.turn { border-radius: 10px; padding: .75rem 1rem; margin: .75rem 0; }
.user { background: #e7f0ff; border: 1px solid #c7dbff; }
.assistant { background: #fff; border: 1px solid #e3e3e3; }
.role { font-weight: 600; font-size: .8rem; text-transform: uppercase;
        letter-spacing: .04em; color: #555; margin-bottom: .35rem; }
.assistant code { background: #f0f0f0; padding: 0 .25rem; border-radius: 3px;
                  font-size: .9em; }
.steps { margin: .25rem 0 .6rem; font-size: .85rem; }
.steps summary { cursor: pointer; color: #666; }
.step { margin: .35rem 0; }
.step .args { color: #777; }
pre { background: #f5f5f5; border: 1px solid #e0e0e0; border-radius: 6px;
      padding: .5rem .6rem; overflow-x: auto; font-size: .8rem; white-space: pre; }
ul { margin: .3rem 0; }
"""


def history_to_html(history, title: str = "Assistant conversation") -> str:
    """Render the conversation as a single self-contained HTML file."""
    ts = datetime.now().strftime("%Y-%m-%d %H:%M")
    parts = [
        "<!DOCTYPE html>", '<html lang="en"><head><meta charset="utf-8">',
        '<meta name="viewport" content="width=device-width, initial-scale=1">',
        f"<title>{escape(title)}</title><style>{_HTML_CSS}</style></head><body>",
        f"<h1>{escape(title)}</h1>",
        f'<div class="meta">Exported {ts} &middot; {_count_turns(history)} exchange(s)'
        ' &middot; every number comes from a validated engine tool, not the language model.</div>',
    ]
    for msg in history or []:
        if msg.get("role") == "user":
            parts.append('<div class="turn user"><div class="role">You</div>'
                         f'<div>{_md_inline(msg.get("content", ""))}</div></div>')
        else:
            steps = _events_html(msg.get("events"))
            parts.append('<div class="turn assistant"><div class="role">Assistant</div>'
                         f'{steps}{_answer_html(msg.get("content", ""))}</div>')
    parts.append("</body></html>")
    return "\n".join(parts)


if __name__ == "__main__":
    demo = [
        {"role": "user", "content": "Is the Spinel stable on a 60% slope?"},
        {"role": "assistant",
         "content": "**Yes - stable.** Governing case is roadside 30% at **SF 2.11**, "
                    "well above 1.0.\n\n- Ascending 60%: SF 2.21\n- Cornering: SF 3.12\n\n"
                    "Limiting axis is lateral [source: mobility_formulas.md].",
         "events": [
             {"type": "tool_call", "name": "run_mobility_check",
              "args": {"variant": "measured"}},
             {"type": "tool_result", "name": "run_mobility_check",
              "content": "MOBILITY ANALYSIS\n  GW: 17,850 kg\n  Governing: roadside 30% SF=2.1088"},
         ]},
    ]
    md = history_to_markdown(demo, "Mobility assistant - demo")
    html = history_to_html(demo, "Mobility assistant - demo")
    print("MARKDOWN chars:", len(md), "| HTML chars:", len(html))
    print("HTML well-formed:", html.startswith("<!DOCTYPE html>") and html.rstrip().endswith("</html>"))
    print("\n----- MARKDOWN -----\n", md[:400])
